version: '3.5'

services:
  puppet:
    hostname: puppet
    domainname: test
    image: ${PUPPET_TEST_DOCKER_IMAGE:-puppet/puppetserver-standalone}
    expose:
      - 8141
    environment:
      - PUPPETSERVER_HOSTNAME=puppet.test
      - PUPPET_MASTERPORT=8141
      - PUPPERWARE_ANALYTICS_ENABLED=${PUPPERWARE_ANALYTICS_ENABLED:-false}
      - DNS_ALT_NAMES=puppet,puppet.test,${DNS_ALT_NAMES:-}
      - PUPPET_STORECONFIGS=false
      - PUPPET_REPORTS=log
    dns_search: 'test'
    extra_hosts:
      - 'compiler.test:172.22.0.101'
    networks:
      puppetserver_test:
        ipv4_address: 172.22.0.100
        aliases:
          - puppet.test

  compiler:
    hostname: compiler
    domainname: test
    image: ${PUPPET_TEST_DOCKER_IMAGE:-puppet/puppetserver-standalone}
    environment:
      - PUPPERWARE_ANALYTICS_ENABLED=${PUPPERWARE_ANALYTICS_ENABLED:-false}
      - PUPPETSERVER_HOSTNAME=compiler.test
      - CA_ENABLED=false
      - CA_HOSTNAME=puppet.test
      - CA_MASTERPORT=8141
      - PUPPET_STORECONFIGS=false
      - PUPPET_REPORTS=log
    dns_search: 'test'
    extra_hosts:
      - 'puppet.test:172.22.0.100'
    networks:
      puppetserver_test:
        ipv4_address: 172.22.0.101
        aliases:
          - compiler.test

networks:
  puppetserver_test:
    name: puppetserver_test
    ipam:
      config:
        - subnet: 172.22.0.0/16
